### ISSUE TITLE
[Feature Request] Integration of "fps" and "no-correct-pts" option

### ISSUE THREAD

**Issue by adamkex** [cmdrkotori/mpc-qt#106]
These settings are available in mpv.conf

They are useful for videos which report incorrect framerates (most notably HorribleSubs). Especially when being used together with interpolation software such as SVP (freeware on Linux, premium on Windows).

**Comment by cmdrkotori** [comment]
Ok.

**Comment by cmdrkotori** [comment]
A little birdie told me that Horriblesubs can be fixed by using Erai-raws instead. Nonetheless, old encodes are still a problem. In one case, video raced ahead of the audio with SVP, and in another the video lagged.

The root cause of this is naturally the file itself, such incorrect info in the container. The best fix of course is fixing the file, but the average user wouldn't know how to do that. And of course, that would destroy the ability to seed.

I'm not sure that exposing fps and no-correct-pts is a good fix for this. It's very file-specific and also hacky.

**Comment by adamkex** [comment]
SVP has fixed this in mpv. Since I don't have mpc-qt installed I can't verify whether it's also fixed on this app. "[HorribleSubs] Eromanga-sensei - 01 [1080p].mkv" is one of the files which has had this problem before. It's very easy to tell whether the audio is in sync or not by 1:40. If this file works correctly then this issue can be closed or be put on hold.

http://www.svp-team.com/forum/viewtopic.php?id=3706

**Comment by adamkex** [comment]
Do you have this setting enabled? ![image](https://user-images.githubusercontent.com/9314405/40882981-644fcc5a-66f2-11e8-8915-da398489fec0.png)
