### ISSUE TITLE
Window layout glitches in i3-gaps

### ISSUE THREAD

**Issue by Frechdachs** [cmdrkotori/mpc-qt#12]
Whenever I open a video or audio file in mpc-qt it always looks like this:
![01](https://u.rekt.cc/mpc-qt01.png)
This can be fixed by switching to fullscreen and back again:
![02](https://u.rekt.cc/mpc-qt02.png)

There are many actions which make the glitch reappear, like toggling GUI elements (e.g. Ctrl+4) or clicking ``Apply`` or ``OK`` in the options dialog. Like before, it can be fixed by switching to fullscreen and back again.

(I'm using Qt 5.6.0)

**Comment by Frechdachs** [comment]
Updated problem description.

**Comment by cmdrkotori** [comment]
>like toggling GUI elements (e.g. Ctrl+4) or clicking Apply or OK in the options dialog

Feels like the problem is in `updateSize`, perhaps with the use of the geometry functions.  To be fair updateSize doesn't quite work as it should on Windows too. I'll see if I can get i3-gaps working on my machine to test.

In the meantime try pressing Alt+0, which completely bypasses all autosizing code. Perhaps it may be better for your wm to manage the window size in this case.

**Comment by Frechdachs** [comment]
Yep, Alt+0 solves the problem for now.

**Comment by cmdrkotori** [comment]
I've set a sensible default for tiling wm's in 0e0a202.

**Comment by Frechdachs** [comment]
Thanks

**Comment by Frechdachs** [comment]
Hm... On my system neither ``XDG_DESKTOP_SESSION`` nor ``XDG_DATA_DIRS`` is set.

But both ``XDG_CURRENT_DESKTOP`` and ``DESKTOP_SESSION`` (without ``XDG_``) are set to ``i3``.
Your code only seems to check the former two.

**Comment by cmdrkotori** [comment]
I've implemented a more thorough scan in a6eb18e.
