### ISSUE TITLE
crashing when enabling MPRIS

### ISSUE THREAD

**Issue by ahjolinna** [cmdrkotori/mpc-qt#122]
I just tried the lastest version of mpc-qt (commit 789fdb8  and every time I try to enable mpris it crashes, here is [the gdb log](https://gist.github.com/ahjolinna/3fa92f8e4b108567356b1ddc72fa96f3)

PS. biggest difference with my pkgbuild from aur version is that I use clang/llvm compiler instead of gcc. (that reminds me, have you used [clazy](https://github.com/KDE/clazy) yet?)

----

system spec:

```
inxi -b
System:    Host: arch-anywhere Kernel: 4.12.10-1-ck-skylake x86_64 (64 bit) Desktop: KDE Plasma 5.10.5
           Distro: Arch Linux
Machine:   Device: desktop Mobo: ASUSTeK model: Z170 PRO GAMING v: Rev X.0x UEFI: American Megatrends v: 2003 date: 09/19/2016
CPU:       Quad core Intel Core i5-6600K (-MCP-) speed/max: 3554/4400 MHz
Graphics:  Card: NVIDIA GM204 [GeForce GTX 970]
           Display Server: x11 (X.Org 1.19.3) driver: nvidia Resolution: 1920x1080@60.00hz, 1920x1080@60.00hz
           OpenGL: renderer: GeForce GTX 970/PCIe/SSE2 version: 4.5.0 NVIDIA 384.59
Network:   Card: Intel Ethernet Connection (2) I219-V driver: e1000e
Drives:    HDD Total Size: 12114.3GB (94.7% used)
Info:      Processes: 314 Uptime: 22:22 Memory: 6549.1/15966.7MB Client: Shell (bash) inxi: 2.3.27
```

**Comment by cmdrkotori** [comment]
This is another bug that is not present in the debug build.

The trace does not have a meaningful symbol from my side, so it *seems* at first glance that it is during a call originating from the system rather than from me. And it's during a time when it's marshalling a bool value. (there are several.) I'll take a look at this later tonight. Sorry about pushing a bad commit.

**Comment by cmdrkotori** [comment]
Oh boy, you're not gonna believe what the fix was.  😆👌🔫

**Comment by ahjolinna** [comment]
Baka :)
