### ISSUE TITLE
minor mpris issue (maybe)

### ISSUE THREAD

**Issue by ahjolinna** [cmdrkotori/mpc-qt#123]
I'm not 100% sure if this is mpc-qẗ́ issue or kde-connect ...but as this works just fine with bomi I assume its mpc-qt..

(I'm not sure how should I explain this)

everytime I open kde-connect and check "multimedia control" -section on my phone, and select mpc-qt...the seekbar always starts from beginning aka doesn't show the current/real time position.

2nd minor problem is that if the video name really long, it won't rotate so you can see the whole name

I made a small video on my phone so you get a better picture: [link](https://www.dropbox.com/s/sgw5e18a6vfnicg/2017_09_04_16_36_19.mp4?dl=0)

PS. when was the last time you tired the ["clazy"](https://github.com/KDE/clazy) thing (sorry that I'm harping about this), yes...it's still in its early days but its already a useful tool for such young project.

---------

[Qbs 1.9](http://blog.qt.io/blog/2017/09/05/qbs-1-9-released/) was just released with [Qt Creator 4.4 ](http://blog.qt.io/blog/2017/09/05/qt-creator-4-4-0-released/)

**Comment by cmdrkotori** [comment]
Eh it's largely the same mpris implementation as that in Dragon Player, except I use the observer model to track mpv state instead of making direct calls. Interestingly the media control in the tray tracks playback but the kdeconnect app does not, which leads me to believe the I may be triggering a bug in kdeconnect, or I'm not marshalling the timecode correctly, or perhaps 12 updates per second is a bit too much for dbus which might confuse some applications.

**Comment by ahjolinna** [comment]
@cmdrkotori : have you checked how bomi did this? as this did work just with it... : bomi's [mpris.cpp file/source](https://github.com/xylosper/bomi/blob/master/src/bomi/player/mpris.cpp)

anyway, what about the "naming" issue, could you add the (file) name rotation...if missing..that is

-------------

plus latest SailfishOS for Xperia X updates :

-  [Opening Sailfish OS HW Adaptation Source Code for Sony Xperia™ X ](https://blog.jolla.com/xperiax-open-source-hw-adaptation/)
- [Sailfish X (Sony Xperia X) Build Instructions Released](https://www.xda-developers.com/sailfish-x-sony-xperia-x-build-guide/amp/)
- [Sailfish X: new flashing tool and new sales start day](https://blog.jolla.com/sailfish-x-new-sales-start-day/)

and for those who know how, they can create/build their own free version (which does not include at least Alien Dalvik, aka android app support), otherwise its 50€ (for 1 year) for a prebuild version with offical support and Alien Dalvik

for other "community ported" devices support list (status): https://wiki.merproject.org/wiki/Adaptations/libhybris

----

PS. it seems [Firefox v57 has been renamed as Firefox Quantum](https://www.neowin.net/news/mozilla-firefox-57-rebranded-as-firefox-quantum) ...

["homepage"](https://www.mozilla.org/en-US/firefox/quantum/)

**Comment by ahjolinna** [comment]
Small update, with the latest kdeconnect update I can't see the file/video name at all just the full app name and the whole seekbar has now disappeared there's just audio control bar... Which doesn't work either. 

Only the basic play/pause and next/previous track things are working

**Comment by cmdrkotori** [comment]
Seems to me that kdeconnect is breaking itself.

**Comment by ahjolinna** [comment]
@cmdrkotori : I don't know about that as other's mpris implementation has been working just fine, for example like "smplayer, spotify & KDE's Elisa (music player)... and dragon player (all but the name)" ...and probably bomi if it would compile on arch (as it did before), this seems to affect mpc-qt.

have you tried kdeconnect out? [f-droid](https://f-droid.org/en/packages/org.kde.kdeconnect_tp/) & [playstore](https://play.google.com/store/apps/details?id=org.kde.kdeconnect_tp&hl=en) + the desktop app from repo (there is also gnome shell version, and soon sailfishOS port) ...[mailinglist](https://mail.kde.org/pipermail/kdeconnect/) and [phabricator page](https://phabricator.kde.org/tag/kde_connect/)...and lastly [blogpost/news](https://nicolasfella.wordpress.com/) about kdeconnect


there is an Qt and QML MPRIS interface and adaptor from the [nemomobile](https://wiki.merproject.org/wiki/Nemo) project (Jolla/sailfishOS people/community) called [qtmpris](https://github.com/nemomobile/qtmpris)

------

btw. have you thought about making an [patreon](https://www.patreon.com/) or [bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F65184327&utm_medium=issues&utm_source=github) account? ...at least basic paypal

**Comment by ahjolinna** [comment]
@cmdrkotori : here is a new kde-connect blogpost about [volume control (& it's implementation)](https://nicolasfella.wordpress.com/2018/04/30/volume-control-in-kde-connect/)

**Comment by cmdrkotori** [comment]
Most of the bugs are fixed in my personal git.

However, kdeconnect incorrectly calls the Seek command instead of the AbsoluteSeek command to set the time. KDE's desktop applet calls the AbsoluteSeek. This means that repeated taps of the timeline in the mobile app will seek forward by that amount instead of seeking to that spot. Taps by the mpris desktop applet work as expected.

The jumpiness in the desktop applet's timeline was fixed by always clamping to the lowest second.
The desktop applet detects seeks through the metadata property, while kdeconnect does not and continues on at the old time. I don't think this is our bug.

I might be pushing this in a few minutes.
