### ISSUE TITLE
[Feature request] Seek with mousewheel

### ISSUE THREAD

**Issue by luigino** [cmdrkotori/mpc-qt#15]
As per subject, would it be complicated to implement?
Possibly by a custom value.

Thanks

**Comment by cmdrkotori** [comment]
It's not difficult by itself, no.  It involves handling clicks/scrolls on the mpv widget, and sending them back to the relativeSeek slot.

However, mpc-hc uses that action for volume-up volume-down. So in order to do a complete solution I need to get around to implementing shortcut editing in the settings widget. I'm working on that now.

**Comment by cmdrkotori** [comment]
You should be able to set this behavior in the settings dialog now.

https://my.mixtape.moe/nagbom.webm

**Comment by luigino** [comment]
That looks awesome, thanks!

Still, for some reason I can't see the selector.
Perhaps I need a version of Qt newer than 5.4 ?

**Comment by cmdrkotori** [comment]
>Perhaps I need a version of Qt newer than 5.4 ?

Yes, please use 5.5.1 or greater.
