### ISSUE TITLE
1.0?

### ISSUE THREAD

**Issue by fagoatse** [cmdrkotori/mpc-qt#181]
Hi, how about a 1.0 release? I've been using mpc-qt for quite a while and it's really solid. I think it deserves a stable release at this point. However, some distros are reluctant to include it in their repos hence I'm asking and maybe you'd get a nice phoronix news post for more recognition and potential contributions to the code.

**Comment by jbeich** [comment]
85434703caf9 made it worse. mpc-qt v18.03 (or later) is hard to package because mpv v0.29.0 (or later) [requires](https://github.com/mpv-player/mpv/commit/a7f4ecb01299) **unreleased** ffmpeg version. And static linking has downsides:
https://wiki.debian.org/UpstreamGuide#No_inclusion_of_third_party_code
https://fedoraproject.org/wiki/Bundled_Libraries?rd=Packaging:Bundled_Libraries
https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies
https://www.freebsd.org/doc/en/books/porters-handbook/bundled-libs.html

**Comment by cmdrkotori** [comment]
We're not going to have a 1.0.
