### ISSUE TITLE
time to move away from github?

### ISSUE THREAD

**Issue by ahjolinna** [cmdrkotori/mpc-qt#197]
Microsoft Is Said to Have Agreed to Acquire Coding Site GitHub https://developers.slashdot.org/story/18/06/03/2042255/microsoft-is-said-to-have-agreed-to-acquire-coding-site-github

I don't know how you feel about this personally but there is a huge wave of backlash against this and many are already migrating to gitlab (or others)

**Comment by cmdrkotori** [comment]
Yes I suppose it is mildly concerning. But there's no concrete reason to move (yet).

I don't think EEE is possible in this case. Perhaps GVFS is part of EEE, if one were to ignore that Bitbucket also supports it and Gitlab plans to implement it. So nothing is hitting me on my radar.

**Comment by ahjolinna** [comment]
yeah, I get that. I just wonder how fast M$ will fuck github over, as for some reason they are really good at that. Also apparently some smaller business customers who uses github private repos are worried about M$ : https://twitter.com/nixcraft/status/1003388106626629632

-----------

PS. star wars han solo (the SJW) movie flopped so badly that it seems Disney wont even get their money back :'D ([link](https://screenrant.com/solo-box-office-bomb-break-even/)) 

if you are interested; [here](https://youtu.be/_bQbYmLAZ_k) is a great review of it, he made also a 4 hour (3 parts) review of how bad Last Jedi was : [part1](https://www.youtube.com/watch?v=vw7pcCj0ORk)

**Comment by ahjolinna** [comment]
https://twitter.com/gitlab/status/1003514208124743680

**Comment by ahjolinna** [comment]
I really hope this is a coincidence: https://www.gentoo.org/news/2018/06/28/Github-gentoo-org-hacked.html

**Comment by cmdrkotori** [comment]
Putting on my tinfoil hat, Gitlab and Github are already compromised, along with most websites in the top 100+. Microsoft and most big tech firms are known to be hand-in-hand with 3LAs (take your pick), so it's a matter of pick your poison. For example, that eBay and Microsoft acquired skype at the government's suggestion is known, and the p2p nature of Skype was removed in short order. It's also quite plausible that Github has been undoubtedly data-mined for quite some time. (in fact, you don't even need to own GitHub for this, almost everything happens in the open.) Ultimately, the only server you can trust is your own.

I am also suspicious of the "community backlash" against this acquisition. The avoidable effect of fleeing Github for other platforms is fragmentation and diminished organization, not to mention the chilling effect of learning a different platform. I'm sure you are aware of recent attempts to sabotage open source through the use of SJWs, and probably where the SJWs come from. This isn't happening in a vacuum. So naturally, Gitlab and """well-meaning users of Github""" (read: fake concern trolls instead of people like you or me) would use social media platforms to manipulate any kneejerk reaction for their own interests ahead of the interests of Gitlab's and GitHub's supposed customers. The people who profit from things like this are the people who don't have to put up with these clearly engineered problems, such as proprietary software companies, the CIA, and other supposedly trustworthy interests who only have their own interests at heart.

I do not believe in coincidences. But the sane choice is to judge our actions by their effect. Moving away is not a wise choice at this stage.
