### ISSUE TITLE
White icon fallback?

### ISSUE THREAD

**Issue by BobbyWibowo** [cmdrkotori/mpc-qt#208]
When using system icon, is there anyway to use the white version of the icon as fallback?
![Image](https://i.fiery.me/KeFG.png)
or perhaps a way to add custom icon to the system which I don't really know how.

**Comment by cmdrkotori** [comment]
Yes, right here.

![screenshot_20180711_163817](https://user-images.githubusercontent.com/11322485/42554596-dbe239d4-8528-11e8-8a73-521a9dc19ecd.png)

**Comment by cmdrkotori** [comment]
Sorry, I misunderstood your request. Fixed properly in master. The icons section in the options window now looks like this:

![screenshot_20180715_201232](https://user-images.githubusercontent.com/11322485/42732840-85a5f4fc-886b-11e8-9eba-d967928d272f.png)

I had to break compatibility with the old options because these new options do not form a 1:1 mapping to the old options. This section will need to be set again. However, the new default on Linux is to use system icons, so it shouldn't be all that much of a jump for you.
