### ISSUE TITLE
pressing "next track" pauses the video instead

### ISSUE THREAD

**Issue by ahjolinna** [cmdrkotori/mpc-qt#210]
now after I got the git version builded and installed on obs/openSUSE, I notice that the "next track" button pauses the video instead.

I have 2 different logs : 
https://paste.kde.org/ppaz2qqm1/dzuuls/raw
https://paste.kde.org/phbront93/ectghm/raw
I haven't installed qt5 debug files...if you need them tell me

PS. and this `warn: Warning: property 'format' was replaced with 'audio-format' and might be removed in the future.`

**Comment by cmdrkotori** [comment]
Thank you for the logs. It seems you're pressing the "step forward" button rather than the "skip forward" button. Press the one that looks like `>>|`, which will skip from chapter marker to chapter marker, or file to file when there are no chapter markers.

>PS. and this `warn: Warning: property 'format' was replaced with 'audio-format' and might be removed in the future.`

I think this is in the libmpv profile inside mpv. We never touch the format property.

**Comment by ahjolinna** [comment]
Yeah it seems like I confused those two buttons... I thought it was vice versa. Anyways when I press the "step forward" (>>|) it pause my video, I think I it shouldn't do anything if there aren't any chapters.

And yes the "skip forward" button did work as it should

**Comment by cmdrkotori** [comment]
I'm referring the appearance of the inbuilt one, *Skip* forward. *Step* forward performs a frame step and pauses. **Skip** forward skips ahead to the next marker.

Some themes (such as Numix Circle) show `>>|` on the rightmost navigation button (frame-step), instead of the inbuilt fallback shows `|>` like the frame-step icon in VirtualDub.

Fallback
![screenshot_20180716_154202](https://user-images.githubusercontent.com/11322485/42744310-e7c48a4c-890e-11e8-8ff9-cc9da0b39af4.png)
Numix circle
![screenshot_20180716_154325](https://user-images.githubusercontent.com/11322485/42744326-003fa96c-890f-11e8-8560-daaf12c705bd.png)
