### ISSUE TITLE
Add ability to define custom mpv options

### ISSUE THREAD

**Issue by chainikdn** [cmdrkotori/mpc-qt#22]
For example to test it with SVP I need to insert "input-ipc-server" option BEFORE mpv_initialize() call.

**Comment by cmdrkotori** [comment]
I've added some functions to mpc-qt's own ipc mechanism which allows this.

However, I'm not quite sure about full-on input-ipc-server support.  While only a single-line fix in line 687 of mpvwidget as of bf49afc, it would be quite trivial to send a loadfile command to mpv and overwrite the metadata of the active file when we get the metadata property. So it would become an attack vector that to be honest makes me nervous. I can emulate the ipc layer though, and filter some things so that I do the Right Thing (tm) in all cases. It certainly would be much better than the current solution, which limits said cases.

Therefore, In near future (a week or so, no promises) I'd like to implement an emulation of mpv's own ipc at `/tmp/cmdrkotori.mpc-qt.mpv` to ease the burden on third-party developers. It would however still be subject to the same restraints as described in the "Internal Mpv Queries" described in the above commit.  On the other hand, it would have the advantage of running in its own thread.  When this happens, the internal state extension of the regular api will be replaced by the emulation layer and might be removed in the future. Please understand.

So if you really want to use svp in the meantime, there's a fix at the top of the svp-support branch which enables potentially unsafe behavior. Have fun. :100: :joy: :ok_hand:

**Comment by cmdrkotori** [comment]
Referred to the wrong issue in git. Sorry about that. It's fixed.

**Comment by wm4** [comment]
mpv's JSON IPC is clearly insecure, and it is documented as such. Access should be allowed only from trusted sources. That's also why we've resisted to add TCP support (instead of just IPC via pipes).

To allow users set options (whether they're security issues or not) before mpv_initialize(), you could set the "config" option to "yes" and "config-dir" to some config directory that is only user-writable.  The mpv_initialize() would load a mpv.conf from there if it exists.

**Comment by cmdrkotori** [comment]
To be honest I too don't like exposing mpv's internal state at all. One option I thought of is to write an emulation layer which does just enough to make svp work without requiring too much on their part. BUT it would require a fair amount on my part, which places the burden on me and is not the ideal situation for us to be in.

However, I would much prefer that svp use a possible setSettingsMap custom ipc that takes arguments in the same format as settings.json, and that settings window has the right options exposed and working for svp to work. This way mpv options could be set safely and nondestructively. For example, I will get to implementing a vf dialog/section eventually, which will likely break whatever svp is doing. So it would be really nice if the svp team would tell me which ones to implement in the gui first, so everything can be above board.

In either case, svp is nonfree software so I can't test it.

**Comment by chainikdn** [comment]
From my point of view I can say that I really don't like the idea that every other libmpv-based video player will re-invent the wheel(s) already invented once in the mpv itself.

> For example, I will get to implementing a vf dialog/section eventually, which will likely break whatever svp is doing.
I don't see real problems here cause we have commands to insert just one filter into the chain and to remove it back.

**Comment by wm4** [comment]
I have to agree with cmdrkotori a bit here. If users can define their own mpv.conf, then they could easily conflict with mpc-qt builtin functionality, such as mpc-qt overwriting the filter list and such. The mpv.conf approach is at best a cheap mechanism to allow the user to do customization on his own risk, but certainly not a general solution.

**Comment by cmdrkotori** [comment]
I've added a emulation interface in the meantime.

When I get around to using filters, it will be possible to add a feature to the main ipc interface such as setPostVideoFilter, with a value in a similar format to that taken by mpv's input-ipc-server.  The value would be inserted after whatever is defined in the settings dialog. The advantage of this would be persistence and no need to track property changes.

I apologize for how long this has taken; the family is moving house and I'm feeling a bit burned out.
