### ISSUE TITLE
settings menu is way to big on low res screens

### ISSUE THREAD

**Issue by ahjolinna** [cmdrkotori/mpc-qt#248]
if you have for example a 720p screen the settings menu screen is way too big and you cant see at least the "OK/Apply/Cancel" buttons. I notice this long time ago on my mothers old VAIO laptop (openSUSE leap 15) but was too lazy to report..
here is a pic from my old ultrabook (manjaro-kde) with resolution turned to 720p (from 1080p) for reference:
![image](https://user-images.githubusercontent.com/6993072/57623200-f1dfd380-7597-11e9-9dfe-8f165a7dc31a.png)

**Comment by cmdrkotori** [comment]
It appears to be the fullscreen page which pushes us over the edge, even with the fusion style and decorations turned off... next in line is the encoding page coming in at about a row of buttons shorter.

In fact, for Windows builds I usually shrink the settings dialog as far as I can before making a build, because Windows widgets are smaller. Before I started doing this, this oversight was pronounced even on a 768px laptop.

Fullscreen page, for reference:
![Screenshot_20190513_232524](https://user-images.githubusercontent.com/11322485/57625398-2030d380-75d7-11e9-9e9d-403d864d0dc4.png)

Maybe that middle section can go to the upper right. It only has to look similar.

**Comment by ahjolinna** [comment]
well up to you, only thing I would say that maybe check [KDE HIG](https://hig.kde.org/)'s for **ideas** how/what to do....I doubt you have any interest moving to QML/[Kirigami](https://techbase.kde.org/Kirigami)
Okay there is a project called [QtMvvm](https://github.com/Skycoder42/QtMvvm)  "library for Qt, to create Projects for Widgets and Quick in parallel" ...this would allow you to have both.

btw. have you been using [clazy](https://github.com/KDE/clazy/) to check the code quality lately?

**Comment by cmdrkotori** [comment]
Default size is now 896x610.

![Screenshot_20190514_115200](https://user-images.githubusercontent.com/11322485/57665892-25c30380-7641-11e9-8acc-b7b0d0d8ae96.png)

**Comment by ahjolinna** [comment]
sorry for the late reply, but it still looks this in 720p (with latest git version):
![image](https://user-images.githubusercontent.com/6993072/57986884-17327d00-7a83-11e9-9bbe-ae9cd39884e8.png)
![image](https://user-images.githubusercontent.com/6993072/57986892-2b767a00-7a83-11e9-9e46-bdce33f50018.png)

**Comment by ahjolinna** [comment]
damn false alarm...I forgot that I had 1.2 scaling on ...thats why it was now too big
