### ISSUE TITLE
Support multi-entry archives

### ISSUE THREAD

**Issue by wm4** [cmdrkotori/mpc-qt#30]
If mpv is compiled against libarchive, it can open compressed archives like zip and rar (at least to a degree). Opening them already works with mpc-qt, except that if the archive contains multiple entries, mpc-qt plays only the first one.

mpv expands archives like directories. It will replace the archive playlist entry with its content (mangled "archive://" entries). When the entry is replaced, playback ends with MPV_END_FILE_REASON_REDIRECT, and then starts playing the first replacement entry. (This might be a pretty bad API - suggestions to improve it are welcome.)

I wonder if mpc-qt could grab the expanded archive contents and somehow expose them on the playlist.

**Comment by cmdrkotori** [comment]
Something similar but not quite the same applies for adding m3u files into the playlists, or inserting them manually through the json config file. The files added simply aren't scanned right now. Furthermore, word documents, text files, and junk can be added even though they don't do anything or may not work as expected. So at the moment mpc-qt will try to play whatever is thrown at it, and assume that every url is atomic, which is not always true.

What's been on my mind for a while is to inspect every file beforehand, (creating extra instances of mpv and inspecting the metadata returned,) then dropping the files if they aren't an actual media file. This would be be a rather good place to fetch any special links (such as playlist expansion), add any internal files as single entries, and prepopulate the playlists with meaningful title data. With this approach, I would not have to handle expanded archive links in any particular special way because the generated links would behave like singular files. However I could imagine some overhead with expanding .tar.gz multiple times, (Ark takes forever to open them,) so perhaps I should just not scan the internal entries after knowing about them.

I'm open to alternatives.

**Comment by wm4** [comment]
> What's been on my mind for a while is to inspect every file beforehand, (creating extra instances of mpv and inspecting the metadata returned,) then dropping the files if they aren't an actual media file. This would be be a rather good place to fetch any special links (such as playlist expansion), add any internal files as single entries, and prepopulate the playlists with meaningful title data.

I don't know, I've disliked this "scanning" always about other players. And the apparent need to scan all entries before even adding them to the playlist would also have UI consequences. (Like a blocking dialog box until it's done?)

> However I could imagine some overhead with expanding .tar.gz multiple times, (Ark takes forever to open them,) so perhaps I should just not scan the internal entries after knowing about them.

mpv isn't particularly efficient here either. libarchive supports only sequential reading for most formats, so opening an archive entry will first skip all preceding entries. With something like tar that requires reading/decompressing all data, this becomes quickly infeasible. Not sure if this is an argument, since normal opening will also be slower, not just collecting metadata.

**Comment by wm4** [comment]
PS: I'm also open for suggestions how to handle such "expanding" entries, beyond just setting the MPV_END_FILE_REASON_REDIRECT flag and mutating the internal playlist.

**Comment by cmdrkotori** [comment]
Well in that case may I suggest a `--no-file-redirect` option, so that mpv enters the idle state after playing the first file in the archive. When playing an archive, clients can let the first file play while inserting mpv's `playlist` property over the item in the playlist window. After the first file ends, the client can pass through the next archive url (if they prefer direct control), or advance the `playlist-pos` property (if they prefer to defer to mpv whenever possible). Either way, this has the benefit that perceived playlist progression matches what happens in mpv, and archive progress can be saved across sessions. So it becomes:

* client listens on `playlist` property
* user plays an archive
* mpv tells client that `playlist` property has changed as usual
* client inspects `playlist`, discovers more than one file
* client inserts data into its own playlist
* first archived file ends
* client sends mpv to the next archived file
* and so on

As for the user changing the archive between sessions, the client which takes control can rightly behave like any extra files were not queued (which they weren't), while the client which defers can insert new files into its playlist as it finds them or ignore them. This may or may not be what mpv does with `watch-later-config`, but it should (still) be correct as far as user interaction goes.

**Comment by wm4** [comment]
> Well in that case may I suggest a --no-file-redirect option, so that mpv enters the idle state after playing the first file in the archive. 

I feel like this would be inconsistent, especially if the playlist should be otherwise fully expanded. This would mean it would simply skip the inserted playlist entries (except the first one). Note that the first entry would change its URL anyway, and the core would signal termination/start events when "redirecting" to it.

Here are some more ideas:
- introduce a "hook" point that allows a client to explicitly deal with this situation by essentially pausing when a redirect happens
- don't expand the playlist inline, but pass the playlist as mpv_node as part of the end file event (but would mpv continue to play the next normal playlist entry?)
- export the originating URL a playlist entry was redirected from in the "playlist" property (may or may not help) - one problem is that an entry could have been redirected multiple times

**Comment by cmdrkotori** [comment]
A hook should be fine.

**Comment by wm4** [comment]
Where exactly should this hook fire?

Currently there's an ``on_unload`` hook, which is called before the end playback event is sent. At this point, the playlist will already be expanded. I could add another hook at "some" point. I thought about putting it after the end event is sent, so that the client can reaffirm the situation properly, but can also use the information provided by the end event. Yes/no?

(And I'm not particularly find of the hook API. But I think it's appropriate here.)

**Comment by cmdrkotori** [comment]
>Where exactly should this hook fire?

The hook contents will essentially be: (from the PlaybackManager persepective)

```
if (nextFileUrl() == mpvw->nextFile())
   okay();
else
   playNextFile();
```
So the desired point would be where this code most efficiently leads to loading the next file.

The bottom line as far as mpc-qt is concerned, is that the hook should fire
* anytime after the last frame is displayed
* before playback of the next item starts, (to avoid painting glitches)
* and probably before the next file is loaded (to avoid the case of loading a file which we don't want)

Anywhere in this period should be ok. Perhaps something close to where idle would otherwise be entered? I presently feed mpv the next link when the playback core is idle because of #18, so it really needs to be when the next file might have a chance of loading and not because the file is being replayed. I'm speaking conceptually here.


>Currently there's an on_unload hook, which is called before the end playback event is sent.

Yes. From the docs, the on_unload hook does look like it satisfies these conditions. I can try this and report back if modification of mpv is actually needed.

**Comment by cmdrkotori** [comment]
Used the hook api as you suggested.

**Comment by wm4** [comment]
Seems to work pretty well.

Feel free to suggest better mechanism for this if something comes to your mind. If I could redo the client API, I'd probably make opening a file (and the file itself) a separate action, and the API user could check what type of thing the result is (e.g. playlist or playable).
