### ISSUE TITLE
C2632: 'bool' followed by 'char' is illegal

### ISSUE THREAD

**Issue by l0phtgh0st** [cmdrkotori/mpc-qt#35]
The method "void relativeSeekRequested(bool fowards, bool small);" located in  source code of "playlistwindow.h", there is a error message "bool followed by char is illegal".

Do you intend the "small" to be a parameter name?

I am compiling it on Windows.

**Comment by cmdrkotori** [comment]
>Do you intend the "small" to be a parameter name?

Yes, afaik small as an alias to char is nonstandard. I've removed the offending function anyway, as it is no longer needed.

>I am compiling it on Windows.

What is your build setup? Compiler, version of Qt, etc. I may be able to test under it at semi-regular intervals.

**Comment by l0phtgh0st** [comment]
I am using QT 5.5.0 with win32-msvc2013.

The ".pro" file is the same as the project, I haven't change anything except adding include and 64 bit of lib (provided by https://mpv.srsfckn.biz/) in the "mpv-dev" folder.

I have also noticed that there is no "mpv.lib" in the link (https://mpv.srsfckn.biz) that you have described.

**Comment by l0phtgh0st** [comment]
I almost forgot ,that you have to add (#include <stdint.h>) in order to recognize "int64_t"

**Comment by l0phtgh0st** [comment]
You have forgot to fix the issue in "manager.h" and "mainwindow.h"

**Comment by cmdrkotori** [comment]
>You have forgot to fix the issue in "manager.h" and "mainwindow.h"

That's because the functions I removed actually weren't needed anymore, the ones in manager.h and mainwindow.h however still are. The root cause of this issue is that the MSVC framework includes a header that #defines small to char.

>I am using QT 5.5.0 with win32-msvc2013.

>there is no "mpv.lib" in the link (https://mpv.srsfckn.biz) that you have described.

I forgot one small thing earlier, I don't support MSVC. That said, you should upgrade your Qt build environment anyway, it's rather old. Now's a good time as ever to switch.
