### ISSUE TITLE
Can't pass filename as command line argument

### ISSUE THREAD

**Issue by luigino** [cmdrkotori/mpc-qt#55]
As per subject. Unless there's a switch I missed, any file passed as argument is ignored.

**Comment by cmdrkotori** [comment]
What's happening is that it tries to play the video before the gl layer is initialized and bails out. (Startup is a bit of race condition at the moment due to wm peculiarities; most of the time it works, except when it doesn't.) The file still ends up in the Quick Playlist however, so if you double click on its item in the playlist window, it will play straight away.

This probably broke a bit ago when I touched the startup code.
