### ISSUE TITLE
[Feature request]: use custom icons

### ISSUE THREAD

**Issue by luigino** [cmdrkotori/mpc-qt#65]
Would it be possible to have different themes at least for the toolbar icons like smplayer?

**Comment by cmdrkotori** [comment]
Yes, but not in the way smplayer does it. There's an icon or two that aren't in any Linux icon pack. So I suspect we'll be going the use-your-own-bitmap route.

**Comment by ahjolinna** [comment]
are you thinking about that mpc-qt should use the "system-icons" or custom "icon pack/theme" that are just made for mpc-qt?

it has always been up to the icon theme creators to add support for different apps so oc there will be icons missing (more or less), easiest way would be to use the most general available icons (names) and add fallback ones.

other option is also that instead of supporting "just" custom icon theme, you would add general theming support that could include the icons...like *{cough}* bomi-player *{cough}* has (more or less) ..and somewhat like smplayer but not as bad

**Comment by cmdrkotori** [comment]
Ricing is a long-term feature that I plan to do after the core functionality is done, so you might be waiting a while.

**Comment by cmdrkotori** [comment]
I recently found the system theme icon names I was looking for (zone-in and zone-out), so we might be fixing this sooner than we think. I just need to think about how the gui would look

As respect multiple themes, the toolbar images are currently in one long svg so they'd need splitting up. Exporting them was a bit of pain anyway. A good time to make a white icon-set too I guess.
