### ISSUE TITLE
Seek bar not functional

### ISSUE THREAD

**Issue by mooop12** [cmdrkotori/mpc-qt#74]
Seek bar doesn't show progress, clicking on it sets video time back to 0, and there are no chapter marks, even though the option is enabled in the settings.

**Comment by cmdrkotori** [comment]
![screenshot_20170330_092800](https://cloud.githubusercontent.com/assets/11322485/24481854/95d372e6-1530-11e7-8c54-33c431258d88.png)

Works for me! Bear in mind some obscure formats have unseekable pts.

**Comment by mooop12** [comment]
This issue is somehow being caused by having `kdebase-runtime` package installed on my system (I'm using Gnome Shell). Do you know what might be the reason for that? I need that package for another program.

**Comment by cmdrkotori** [comment]
Is it all one color? If so, the system palette might be misconfigured.

**Comment by cmdrkotori** [comment]
sorry about that, wrong button.

**Comment by mooop12** [comment]
It looks the same as without `kdebase-runtime`, only the slider and chapter marks are missing. Screenshots below are from the same video file, with the aforementioned package and without.
![screenshot from 2017-03-30 02-41-57](https://cloud.githubusercontent.com/assets/20934112/24482618/0e275fca-14f3-11e7-9404-ef44f988889a.png)
![screenshot from 2017-03-30 02-44-14](https://cloud.githubusercontent.com/assets/20934112/24482615/0af932f6-14f3-11e7-87af-0d54e4141a59.png)

**Comment by cmdrkotori** [comment]
I have plasma full and it works here. What distro? I might be able to reproduce it and fix.

**Comment by cmdrkotori** [comment]
What package are you using that pulls in kdebase-runtime? I'm fairly close to testing for this.

**Comment by mooop12** [comment]
The specific package that pulled kdebase-runtime as a dependency was kdiff3.

I actually stopped using GNOME in the meantime and switched to KDE, mpc-qt is working fine here so I wont be of much help in diagnosing this I'm afraid.

**Comment by cmdrkotori** [comment]
I seem to have it running ok with unaltered code on gnome+gnome-apps+kdiff3 on wayland w/o real hardware. Not that this means anything, because obviously something went wrong in your screenshot.

![screenshot_20170424_232850](https://cloud.githubusercontent.com/assets/11322485/25339469/3c53c598-2946-11e7-85cd-f26d3c256356.png)

So no easy fix, but lots of code staring outside of porting this vm to qemu and testing on actual hw and/or X.org. I'll make a few more attempts to reproduce this, perhaps tomorrow. If I can't reproduce then I'll have to close with caveat emptor, patches welcome. See you in a bit, hopefully it's really simple.

**Comment by mooop12** [comment]
Not sure if that's relevant, but I was using x.org (nvidia drivers don't support wayland).
