### ISSUE TITLE
Build fails after f5a842b

### ISSUE THREAD

**Issue by luigino** [cmdrkotori/mpc-qt#93]
See attachment.
[mpc-qt_fail.txt](https://github.com/cmdrkotori/mpc-qt/files/1042368/mpc-qt_fail.txt)

**Comment by luigino** [comment]
Something in the last four commits made a hash of the interaction with X11.
Now I can't place it properly with wmctrl anymore and even when I can, sometimes the border is counted and sometimes it isn't.

Ironically it looks very much like the problem SMPlayer had when it started being built against Qt5.

**Comment by cmdrkotori** [comment]
I can reproduce the oddity when AlwaysOnTop mode is on, but not with it off. Especially so if AlwaysOnTop is applied at startup. I haven't encountered it escaping wmctrl's notice (yet), but I haven't been trying very hard.

For example when the window is acting strange, `wmctrl -i -r 0x08a00005 -e 0,10,10,1280,720` will reposition the window frame to 10,10 correctly. But a following up call to `wmctrl -i -r 0x08a00005 -e 0,10,10,1280,720` will set the title bar off-screen with the client-side geometry at 10,10. Strange stuff.

If I had to point the finger in the last four commits, I would say that it is almost definitely b009ce8. The other three commits were cleaning up the resizing code which actually resulted in less X11 calls. However b009ce8 causes X11 to actually apply the requested window flags (for AlwaysOnTop) shortly after startup and avoid the window not showing at all. I said in the commit that there's probably a better way to do it. At the time it meant that I can't be bothered doing the research to find out the more-correct method since it appears to work on my end, but I guess that's not the case anymore. The simplest solution in the meantime then is not attempting to manipulate the always on top flag at all. Oh well.
